  name: Translate
  on:
    push:
      branches: [main]
  jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16.x'
            registry-url: 'https://npm.pkg.github.com'
        - run: npm i
        - run: npm run upload:i18n
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}